[build]
  command = "npm ci && npm run build:netlify"
  publish = "build"

[build.environment]
  REACT_APP_FORCE_DEMO_MODE = "true"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  CI = "false"
  NODE_VERSION = "18.19.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/static/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable" 